[workspace]
resolver = "3"
members = [
    "srobo_base",
    "im920_rs",
    "rust_test",
]

[patch.crates-io]
srobo_base = { path = "srobo_base", feature = ["std"] }
im920_rs = { path = "im920_rs" }
